name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Vilmanaka
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1
      - name: Build Go application
        run: go build -o vilmanaka-bot

      - name: Set mode to production
        run: |
          rm .env
          cp .env.production .env

      - name: Deleting things
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf /root/vilmanaka-bot
            mkdir -p /root/vilmanaka-bot

      - name: Deploy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./vilmanaka-bot,./.env,./messages"
          target: "/root/vilmanaka-bot"

      - name: Deploy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./vilmanaka-bot.service"
          target: "/etc/systemd/system"

      - name: Enable and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            systemctl daemon-reload
            systemctl enable --now vilmanaka-bot
            systemctl restart vilmanaka-bot