name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    environment: Vilmanaka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1
      - name: Build Go application
        run: go build -o vilmanaka-bot

      - name: Deploy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "./vilmanaka-bot"
          target: "/root"

      - name: Deploy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "./vilmanaka-bot.service"
          target: "/etc/systemd/system"

      - name: Enable and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: systemctl enable --now vilmanaka-bot